server {
    listen 8080;
    server_name _;
    root /workspace/compat/laravel-smoke/public;
    access_log off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /workspace/compat/laravel-smoke/public/index.php;
        fastcgi_param DOCUMENT_ROOT /workspace/compat/laravel-smoke/public;
        fastcgi_pass fpm:9000;
        fastcgi_keep_conn on;
    }
}
